// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWDB48LIoOmSja2OW1WfcZkXOTg-V95wY',
    appId: '1:63263521757:web:d95295e609a55974b45434',
    messagingSenderId: '63263521757',
    projectId: 'medidoriv',
    authDomain: 'medidoriv.firebaseapp.com',
    storageBucket: 'medidoriv.firebasestorage.app',
    databaseURL: 'https://medidoriv-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz5q4GtMnj9Bc4G63uurGi9IZEg1uYP5Y',
    appId: '1:63263521757:android:27afb585b5563eaeb45434',
    messagingSenderId: '63263521757',
    projectId: 'medidoriv',
    storageBucket: 'medidoriv.firebasestorage.app',
    databaseURL: 'https://medidoriv-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKjwWOo6NqGctzs6J0wt-7bJMCI1WPqbE',
    appId: '1:63263521757:ios:a36879262fd584fab45434',
    messagingSenderId: '63263521757',
    projectId: 'medidoriv',
    storageBucket: 'medidoriv.firebasestorage.app',
    iosBundleId: 'com.example.medidoriv',
    databaseURL: 'https://medidoriv-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKjwWOo6NqGctzs6J0wt-7bJMCI1WPqbE',
    appId: '1:63263521757:ios:a36879262fd584fab45434',
    messagingSenderId: '63263521757',
    projectId: 'medidoriv',
    storageBucket: 'medidoriv.firebasestorage.app',
    iosBundleId: 'com.example.medidoriv',
    databaseURL: 'https://medidoriv-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDB48LIoOmSja2OW1WfcZkXOTg-V95wY',
    appId: '1:63263521757:web:ff66a47e3553172bb45434',
    messagingSenderId: '63263521757',
    projectId: 'medidoriv',
    authDomain: 'medidoriv.firebaseapp.com',
    storageBucket: 'medidoriv.firebasestorage.app',
    databaseURL: 'https://medidoriv-default-rtdb.firebaseio.com/',
  );
}
